appName: Test App134
server:
  host: localhost
  port: 8888
  writeTimeout: 15
  readTimeout: 15
  readHeaderTimeout: 15
environment: development
enableLog: true
auth0:
  domain: goauth.au.auth0.com
  client_id: 1321RR33MJmg900AQPrFkX2a6hJnrWiW
  client_secret: fVUc-xAbRT90Rpsr4aMwCXvGFdoZV5FuboseFCXIDzsM_vsYPgYXsGyi-wNmFfg_
  audience: https://goauth.au.auth0.com/api/v2/